name: cureways_user
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.0
  dropdown_button2: ^2.0.0
  pie_chart: ^5.3.2
  carousel_slider: ^4.2.1
  fl_chart: ^0.62.0
  http: ^1.1.0
  # for store local storage
  shared_preferences: ^2.0.17
  syncfusion_flutter_charts: ^21.2.4
  cached_network_image: ^3.2.3
  fluttertoast: ^8.1.2
  google_sign_in: ^6.1.4
  get: ^4.6.6
  shimmer: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.2.2
  logger: ^2.0.2+1
  image_cropper: ^5.0.1
  flutter_screenutil: ^5.9.0
  intl_phone_number_input: ^0.7.4
  image_picker: ^0.8.8
  dio: ^5.4.0
  flutter_spinkit: ^5.2.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/home_screen/
    - assets/welcome_screen/
    - assets/doctor_image/
    - assets/blood_bank/
    - assets/ambulance/
    - assets/vaccine/
    - assets/health_tracker/
    - assets/health_profile/
    - assets/health_tips/
    - assets/images/
    - assets/icons/
    - assets/home/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Black.ttf
          weight: 900
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Urbanist-Thin.ttf
          weight: 100
